name: dravetech
description: Network + Software + Imagination = Awesomness
url: http://0.0.0.0:4000

excerpt_separator: <!--more-->

highlighter: pygments
paginate: 5
defaults:
  -
    scope:
      path: "blog"
    values:
      layout: "blog"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "blogpost"
  -
    scope:
      path: ""
      type: "drafts"
    values:
      layout: "blogpost"
  -
    scope:
      path: "tag"
    values:
      layout: "tag"
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
