name: David Barroso´s Blog
description: Yet another blog
url: https://dbarrosop.github.io

excerpt_separator: <!--more-->

highlighter: pygments
paginate: 5
defaults:
  -
    scope:
      path: "blog"
    values:
      layout: "blog"  
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "blogpost"
  -
    scope:
      path: ""
      type: "drafts"
    values:
      layout: "blogpost"
  -
    scope:
      path: "tag"
    values:
      layout: "tag"
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
